// Icon resource

#include <Windows.h>

const char Icon_32x32[] = {
	'\0', '\0', '\x01', '\0', '\x01', '\0', ' ', ' ', '\0', '\0', '\x01', '\0', ' ', '\0', '\xA8', '\x10', 
    '\0', '\0', '\x16', '\0', '\0', '\0', '(', '\0', '\0', '\0', ' ', '\0', '\0', '\0', '@', '\0', 
    '\0', '\0', '\x01', '\0', ' ', '\0', '\0', '\0', '\0', '\0', '\0', '\x10', '\0', '\0', '\0', '\0', 
    '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\xB5', '\x86', 
    '\xEF', '\xF0', '\xB5', '\x86', '\xEF', '\xFC', '\xB1', '\x84', '\xE8', '\xFC', '\xB2', '\x88', '\xDE', '\xFC', '\xA5', '\x80', 
    '\xC5', '\xFC', '\xB5', '\x96', '\xC9', '\xFC', '\xA3', '\x87', '\xAB', '\xFC', '\x88', 'l', '\x89', '\xFC', 'w', '4', 
    's', '\xFC', 'R', '&', '\xB8', '\xFC', 'L', '!', 'J', '\xFC', '!', '\x13', 'b', '\xFC', 'e', 'N', 
    '\x8B', '\xFC', '\x9D', '\x83', '\x99', '\xFC', 'F', ',', 'I', '\xFC', '+', '\x14', 'h', '\xFC', '5', '\x16', 
    'O', '\xFC', 'K', ':', 'o', '\xFC', ';', 'V', '\x8C', '\xFC', '\x82', 'r', '\x86', '\xFC', '\x88', '}', 
    '\x97', '\xFC', '\xA5', '\x94', '\xA8', '\xFC', '\xBC', '\xAD', '\xB1', '\xFC', '\xD5', '\xD3', '\xD4', '\xFC', '\xDC', '\xD8', 
    '\xD8', '\xFC', '\xEF', '\xEB', '\xED', '\xFC', '\xDA', '\xD6', '\xD8', '\xFC', '\xDF', '\xDA', '\xDC', '\xFC', '\xE8', '\xE5', 
    '\xE6', '\xFC', '\xE1', '\xDF', '\xE1', '\xFC', '\xCA', '\xC4', '\xCF', '\xFC', '\xB8', '\x96', '\xDC', '\xF0', '\xB5', '\x86', 
    '\xEF', '\xFC', '\xB5', '\x86', '\xEE', '\xFF', '\xB3', '\x85', '\xEB', '\xFF', '\xAC', '\x80', '\xE1', '\xFF', '\x99', 'u', 
    '\xC5', '\xFF', '\xB5', '\x86', '\xEF', '\xFF', '\xB5', '\x87', '\xEE', '\xFF', '\xAA', '}', '\xDD', '\xFF', 'V', ')', 
    'y', '\xFF', 'B', '\x1E', 'H', '\xFF', 'f', 'O', 'x', '\xFF', '3', ' ', 's', '\xFF', '\xA0', '\x89', 
    '\x98', '\xFF', '\xB2', '\xA3', '\xA9', '\xFF', '\x96', '\x8D', '\x94', '\xFF', '\x96', '\x83', '\x87', '\xFF', 'O', '7', 
    'T', '\xFF', 'W', 'B', 'w', '\xFF', 'Y', 'd', '\x8F', '\xFF', ']', 'g', '~', '\xFF', '\x80', 'l', 
    '\x7F', '\xFF', '\x87', 'z', '\x9C', '\xFF', '\x9B', '\x88', '\x9C', '\xFF', '\xB8', '\xAD', '\xB1', '\xFF', '\xE3', '\xE0', 
    '\xE1', '\xFF', '\xDC', '\xD7', '\xD6', '\xFF', '\xFA', '\xF2', '\xF2', '\xFF', '\xF6', '\xEB', '\xE9', '\xFF', '\xEA', '\xE2', 
    '\xE2', '\xFF', '\xCB', '\xBC', '\xD8', '\xFF', '\xB5', '\x8D', '\xE4', '\xFF', '\xB5', '\x86', '\xEF', '\xFC', '\xB5', '\x87', 
    '\xEF', '\xFC', '\xB6', '\x88', '\xEF', '\xFF', '\xA7', '{', '\xD4', '\xFF', '\x95', 'u', '\xC9', '\xFF', ']', '\\', 
    '\x9B', '\xFF', '\xB5', '\x87', '\xEF', '\xFF', '\xB5', '\x87', '\xEF', '\xFF', '\xB5', '\x87', '\xEE', '\xFF', '\x84', '\\', 
    '\xB6', '\xFF', '\x92', 'i', '\xBD', '\xFF', '\xB1', '\x84', '\xDD', '\xFF', '\x9E', '\x86', '\x93', '\xFF', '\xB7', '\x9E', 
    '\x9B', '\xFF', '\xAA', '\xA0', '\xAD', '\xFF', '\x89', '\x9B', '\xC7', '\xFF', '\xB9', '\xA9', '\xA9', '\xFF', '\xC8', '\xAE', 
    '\xA4', '\xFF', '\xE7', '\xC8', '\xBE', '\xFF', '\xDF', '\xC2', '\xB9', '\xFF', '9', 'd', '\xA3', '\xFF', '5', 'C', 
    'Y', '\xFF', '\x10', '!', ':', '\xFF', '3', ';', '_', '\xFF', '\x95', 'v', '\xAB', '\xFF', '\x98', '\x88', 
    '\xA0', '\xFF', '\xDA', '\xD4', '\xDB', '\xFF', '\xDE', '\xD7', '\xD6', '\xFF', '\xF0', '\xE3', '\xDF', '\xFF', '\xD9', '\xC9', 
    '\xE0', '\xFF', '\xB2', '\x87', '\xE5', '\xFF', '\xB5', '\x87', '\xEF', '\xFF', '\xB5', '\x87', '\xEF', '\xFC', '\xB5', '\x8A', 
    '\xEF', '\xFC', '\xB5', '\x8A', '\xEF', '\xFF', '\xA5', '{', '\xD0', '\xFF', 'Q', 'b', '\xAD', '\xFF', ' ', 'E', 
    '\x85', '\xFF', 'b', 'T', '\x8B', '\xFF', '\x8B', 'm', '\xB8', '\xFF', 'u', ']', '\x9B', '\xFF', '\x89', 'g', 
    '\xA9', '\xFF', '\x9A', 's', '\xBC', '\xFF', 'f', 'T', '\x86', '\xFF', 'r', 'h', 'q', '\xFF', '\xA6', '\x92', 
    '\x8B', '\xFF', '\x95', '\x9B', '\xB8', '\xFF', '\x8C', '\xA2', '\xCE', '\xFF', '\x89', '\x99', '\xC1', '\xFF', '\x93', '\x8F', 
    '\x9D', '\xFF', '\xB7', '\xA8', '\xAF', '\xFF', '\xCF', '\xB5', '\xAE', '\xFF', '\xBF', '\xAD', '\xAF', '\xFF', '#', 'W', 
    '\x9C', '\xFF', '\x0E', '%', 'F', '\xFF', '\x15', '\'', 'D', '\xFF', '\x97', 'y', '\xCB', '\xFF', '\xB6', '\x8B', 
    '\xEF', '\xFF', '\xB3', '\x87', '\xEB', '\xFF', '\xB1', '\x89', '\xE0', '\xFF', '\xB0', '\x87', '\xE1', '\xFF', '\xB4', '\x88', 
    '\xED', '\xFF', '\xB5', '\x8A', '\xEF', '\xFF', '\xB5', '\x8A', '\xEF', '\xFF', '\xB5', '\x8A', '\xEF', '\xFC', '\xB5', '\x8B', 
    '\xEF', '\xFC', '\xB6', '\x8C', '\xEF', '\xFF', '\x9F', 'v', '\xC5', '\xFF', '1', 'X', '\xA3', '\xFF', '\x12', '-', 
    'W', '\xFF', '\x16', '5', 'j', '\xFF', '\r', '\x1F', '8', '\xFF', '\r', '$', '@', '\xFF', '\x16', ')', 
    'G', '\xFF', '(', '2', 'T', '\xFF', 'U', 'M', '\x7F', '\xFF', 'Q', 'G', 'h', '\xFF', '\x92', '\x80', 
    '|', '\xFF', '\x81', '\x95', '\xC2', '\xFF', '\x8A', '\x9C', '\xC5', '\xFF', '\xB0', '\xBE', '\xDB', '\xFF', '\xCB', '\xD8', 
    '\xEF', '\xFF', '\xB2', '\xBE', '\xD6', '\xFF', '\x95', '\xA3', '\xBD', '\xFF', 'v', 'x', '\x89', '\xFF', ',', 'A', 
    'b', '\xFF', '\x1A', 'N', '\x96', '\xFF', '\x10', '(', 'M', '\xFF', 'N', 'I', 'x', '\xFF', '\xB3', '\x8D', 
    '\xED', '\xFF', '\xB5', '\x8B', '\xEF', '\xFF', '\xB5', '\x8B', '\xEF', '\xFF', '\xB5', '\x8B', '\xEF', '\xFF', '\xB5', '\x8B', 
    '\xEF', '\xFF', '\xB5', '\x8B', '\xEF', '\xFF', '\xB5', '\x8B', '\xEF', '\xFF', '\xB5', '\x8B', '\xEF', '\xFC', '\xBC', '\x8E', 
    '\xEF', '\xFC', '\xBC', '\x8E', '\xEF', '\xFF', '\x98', 's', '\xBB', '\xFF', '2', 'V', '\x9F', '\xFF', '\x0E', '\'', 
    'I', '\xFF', '\x0E', '&', 'H', '\xFF', '\x15', '5', 'j', '\xFF', '\n', '\x1C', '3', '\xFF', '\v', '\x1D', 
    '4', '\xFF', '\n', '!', ';', '\xFF', '\v', '$', 'B', '\xFF', '\x0F', '$', '@', '\xFF', '\x12', '%', 
    '=', '\xFF', '\x8D', '\x9A', '\xB2', '\xFF', '\xD6', '\xE1', '\xF9', '\xFF', '\xDD', '\xE8', '\xFF', '\xFF', '\xDF', '\xEA', 
    '\xFF', '\xFF', '\xDE', '\xE9', '\xFF', '\xFF', '\xDC', '\xE7', '\xFF', '\xFF', '\xD2', '\xDD', '\xF4', '\xFF', '\x80', '\x90', 
    '\xA9', '\xFF', ')', 'E', 'o', '\xFF', '\x1D', 'Q', '\x9B', '\xFF', '\x1A', '1', '[', '\xFF', '\x94', 'z', 
    '\xC5', '\xFF', '\xBB', '\x8E', '\xEF', '\xFF', '\xBC', '\x8E', '\xEF', '\xFF', '\xBC', '\x8E', '\xEF', '\xFF', '\xBC', '\x8E', 
    '\xEF', '\xFF', '\xBC', '\x8E', '\xEF', '\xFF', '\xBC', '\x8E', '\xEF', '\xFF', '\xBC', '\x8E', '\xEF', '\xFC', '\xAB', '\x82', 
    '\xD6', '\xFC', '\xBC', '\x8F', '\xEE', '\xFF', '\x98', 'u', '\xBE', '\xFF', 'P', 'Z', '\x9A', '\xFF', '\x11', ',', 
    'T', '\xFF', '\t', '$', 'B', '\xFF', '\r', '&', 'H', '\xFF', '\x13', '/', ']', '\xFF', '\v', '$', 
    'A', '\xFF', '\n', '"', '=', '\xFF', '\f', ' ', ':', '\xFF', '0', '@', 'X', '\xFF', '\xB6', '\xC2', 
    '\xD7', '\xFF', '\xDB', '\xE6', '\xFE', '\xFF', '\xDE', '\xEA', '\xFF', '\xFF', '\xDF', '\xEB', '\xFF', '\xFF', '\xE6', '\xEE', 
    '\xFF', '\xFF', '\xE0', '\xEB', '\xFF', '\xFF', '\xE0', '\xEB', '\xFF', '\xFF', '\xDE', '\xEA', '\xFF', '\xFF', '\xDC', '\xE7', 
    '\xFE', '\xFF', '\xCE', '\xDA', '\xF2', '\xFF', 'R', 'k', '\x8F', '\xFF', '\x1E', 'S', '\xA0', '\xFF', 'D', 'N', 
    '\x87', '\xFF', '\xB4', '\x90', '\xEA', '\xFF', '\xBD', '\x90', '\xEF', '\xFF', '\xBD', '\x90', '\xEF', '\xFF', '\xBD', '\x90', 
    '\xEF', '\xFF', '\xBD', '\x90', '\xEF', '\xFF', '\xBD', '\x90', '\xEF', '\xFF', '\xBD', '\x90', '\xEF', '\xFC', '\x95', '|', 
    '\xC6', '\xFC', 'A', 'N', '\x85', '\xFF', '\x89', 'o', '\xB1', '\xFF', 'N', 'H', 'r', '\xFF', '\x15', '2', 
    'b', '\xFF', '\n', '$', 'B', '\xFF', '\b', '$', 'B', '\xFF', '\t', '$', 'B', '\xFF', '\b', '$', 
    'B', '\xFF', '\v', '$', 'B', '\xFF', '8', 'I', 'a', '\xFF', '\xCB', '\xD7', '\xEE', '\xFF', '\xDD', '\xE8', 
    '\xFF', '\xFF', '\xE0', '\xEB', '\xFF', '\xFF', '\xDE', '\xE9', '\xFD', '\xFF', '\xA7', '\xAB', '\xE4', '\xFF', '\x96', '\x98', 
    '\xF0', '\xFF', '\x8E', '\x90', '\xD7', '\xFF', '\xC9', '\xD2', '\xEE', '\xFF', '\xE0', '\xEB', '\xFF', '\xFF', '\xDF', '\xEB', 
    '\xFF', '\xFF', '\xDB', '\xE6', '\xFA', '\xFF', '\xB5', '\xBE', '\xCF', '\xFF', '=', 'W', '\x83', '\xFF', ' ', 'U', 
    '\xA6', '\xFF', 'z', 's', '\xBA', '\xFF', '\xBC', '\x93', '\xEE', '\xFF', '\xBD', '\x93', '\xEF', '\xFF', '\xBD', '\x93', 
    '\xEF', '\xFF', '\xBD', '\x93', '\xEF', '\xFF', '\xBD', '\x93', '\xEF', '\xFF', '\xBD', '\x93', '\xEF', '\xFC', '\xA7', '\x86', 
    '\xD5', '\xFC', '\x1C', '?', 't', '\xFF', '\x1E', '@', '~', '\xFF', ' ', '-', 'P', '\xFF', '\x0F', '%', 
    'I', '\xFF', '\r', '\'', 'J', '\xFF', '\t', '$', 'B', '\xFF', '\n', '\x1F', '6', '\xFF', '\b', '$', 
    'A', '\xFF', '\x12', '&', 'C', '\xFF', '\xC0', '\xCB', '\xE0', '\xFF', '\xDE', '\xEA', '\xFF', '\xFF', '\xDE', '\xEB', 
    '\xFF', '\xFF', '\xE0', '\xEB', '\xFF', '\xFF', '\xAA', '\xB0', '\xD9', '\xFF', '\x8C', '\x8C', '\xE9', '\xFF', '\x89', '\x8A', 
    '\xE8', '\xFF', '\x86', '\x86', '\xE7', '\xFF', '~', '\x81', '\xD1', '\xFF', '\xDF', '\xEA', '\xFF', '\xFF', '\xDE', '\xEA', 
    '\xFF', '\xFF', '\xDE', '\xE9', '\xFF', '\xFF', '\xD4', '\xDD', '\xF2', '\xFF', 'X', 'i', '\x8A', '\xFF', '\x98', '\xA6', 
    '\xBE', '\xFF', 'N', 'n', '\xAC', '\xFF', '\xA4', '\x8B', '\xDB', '\xFF', '\xBD', '\x97', '\xEF', '\xFF', '\xBD', '\x97', 
    '\xEF', '\xFF', '\xBD', '\x97', '\xEF', '\xFF', '\xBD', '\x97', '\xEF', '\xFF', '\xBD', '\x97', '\xEF', '\xFC', '\xBC', '\x96', 
    '\xE8', '\xFC', ')', 'J', '\x86', '\xFF', '\x10', '\'', 'L', '\xFF', '\x1D', 'G', '\x90', '\xFF', '\x10', '(', 
    'L', '\xFF', '\x0F', '\'', 'K', '\xFF', '\t', '\x1D', '4', '\xFF', '\n', '$', 'A', '\xFF', '\x1B', '0', 
    'J', '\xFF', 'm', 'w', '\x89', '\xFF', '\xDC', '\xE6', '\xFF', '\xFF', '\xD4', '\xDE', '\xF3', '\xFF', '\xDE', '\xE9', 
    '\xFF', '\xFF', '\xDE', '\xE8', '\xFF', '\xFF', '\x85', '\x88', '\xB6', '\xFF', 'a', 'c', '\xB8', '\xFF', '~', '\x80', 
    '\xC0', '\xFF', '\x82', '\x85', '\xC0', '\xFF', '\x83', '\x87', '\xB9', '\xFF', '\xDA', '\xE3', '\xF9', '\xFF', '\xDB', '\xE3', 
    '\xFF', '\xFF', '\xD7', '\xE0', '\xFF', '\xFF', '\xD7', '\xE0', '\xFF', '\xFF', '\x91', '\xA2', '\xC7', '\xFF', '7', '^', 
    '\xA0', '\xFF', '\x8F', '\x9F', '\xBA', '\xFF', '{', '\x87', '\xBF', '\xFF', '\xC0', '\x9A', '\xEF', '\xFF', '\xC2', '\x9A', 
    '\xEF', '\xFF', '\xC2', '\x9A', '\xEF', '\xFF', '\xC2', '\x9A', '\xEF', '\xFF', '\xC1', '\x9A', '\xEF', '\xFC', '\x8C', '|', 
    '\xC1', '\xFC', 'R', 'd', '\xAA', '\xFF', '\x10', ')', 'M', '\xFF', '\x14', '1', '`', '\xFF', '\x1E', 'N', 
    '\x9A', '\xFF', '\x0E', '%', 'F', '\xFF', '\n', '\x1D', '3', '\xFF', '\x17', '-', 'G', '\xFF', '\x91', '\x9B', 
    '\xAE', '\xFF', '\xA2', '\xAC', '\xC3', '\xFF', '\x97', '\x9E', '\xB5', '\xFF', '\xC4', '\xCC', '\xEA', '\xFF', '\xD7', '\xDF', 
    '\xFF', '\xFF', '\xDB', '\xE3', '\xFF', '\xFF', '\xDE', '\xE6', '\xFE', '\xFF', '\xD9', '\xE3', '\xF7', '\xFF', '\xD8', '\xE3', 
    '\xF7', '\xFF', '\xDF', '\xEB', '\xFF', '\xFF', '\xDE', '\xE8', '\xFF', '\xFF', '\xDA', '\xE2', '\xFF', '\xFF', '\xCD', '\xD4', 
    '\xFF', '\xFF', '\xC6', '\xCC', '\xFE', '\xFF', '\xC8', '\xCD', '\xFE', '\xFF', '\xCC', '\xD5', '\xFC', '\xFF', '1', ']', 
    '\xA3', '\xFF', '?', '_', '\x95', '\xFF', '\x81', '\x92', '\xB4', '\xFF', '~', '{', '\xC8', '\xFF', '\xC6', '\x9D', 
    '\xEF', '\xFF', '\xC6', '\x9D', '\xEF', '\xFF', '\xC6', '\x9D', '\xEF', '\xFF', '\xC6', '\x9D', '\xEF', '\xFC', '%', '[', 
    '\xA9', '\xFC', '1', 'C', 's', '\xFF', '\x18', '<', 'w', '\xFF', '\x10', '%', 'J', '\xFF', '\x1E', 'M', 
    '\x97', '\xFF', '\x14', '1', '_', '\xFF', '\v', ' ', '9', '\xFF', 'u', '\x7F', '\x93', '\xFF', 'v', '\x8E', 
    '\xBA', '\xFF', '9', 'T', '{', '\xFF', '\x93', '\x9F', '\xCC', '\xFF', '\xC7', '\xCE', '\xFF', '\xFF', '\xCB', '\xD2', 
    '\xFF', '\xFF', '\xD3', '\xDB', '\xFF', '\xFF', '\xDA', '\xE3', '\xFF', '\xFF', '\xDE', '\xE8', '\xFF', '\xFF', '\xD3', '\xDF', 
    '\xF1', '\xFF', '\xE0', '\xEC', '\xFF', '\xFF', '\xDE', '\xE8', '\xFF', '\xFF', '\xD9', '\xE0', '\xFF', '\xFF', '\xCC', '\xD2', 
    '\xFF', '\xFF', '\xBF', '\xC3', '\xF5', '\xFF', '\xA9', '\xAD', '\xD9', '\xFF', '\xB2', '\xB7', '\xD6', '\xFF', 'h', '\x85', 
    '\xBB', '\xFF', '\x1F', 'U', '\xA4', '\xFF', 'j', '\x7F', '\xA2', '\xFF', '*', 'H', '}', '\xFF', '\xB1', '\x93', 
    '\xDE', '\xFF', '\xC6', '\xA0', '\xEF', '\xFF', '\xC6', '\xA0', '\xEF', '\xFF', '\xC6', '\xA0', '\xEF', '\xFC', '\x1D', '\\', 
    '\xAF', '\xFC', '\x1D', 'R', '\x9E', '\xFF', '\x19', '?', '~', '\xFF', '\x11', '*', 'R', '\xFF', '\x15', '6', 
    'k', '\xFF', '\x18', '7', 'm', '\xFF', '.', 'A', '[', '\xFF', 'k', '\x81', '\xA9', '\xFF', 'I', 'h', 
    '\x99', '\xFF', '.', 'V', '\x97', '\xFF', '\xCA', '\xD1', '\xFE', '\xFF', '\xC3', '\xC9', '\xFC', '\xFF', '\xCC', '\xD3', 
    '\xFF', '\xFF', '\xD4', '\xDC', '\xFF', '\xFF', '\xDC', '\xE4', '\xFF', '\xFF', '\xDE', '\xE8', '\xFF', '\xFF', '\xE0', '\xEB', 
    '\xFF', '\xFF', '\xE1', '\xEB', '\xFF', '\xFF', '\xDE', '\xEA', '\xFF', '\xFF', '\xDD', '\xE6', '\xFF', '\xFF', '\xD6', '\xDF', 
    '\xFF', '\xFF', '\xD2', '\xDA', '\xFF', '\xFF', '\xD6', '\xDE', '\xFF', '\xFF', '\xC6', '\xCE', '\xEA', '\xFF', 'A', '\\', 
    '\x8A', '\xFF', ' ', 'W', '\xAB', '\xFF', '<', 'b', '\x9B', '\xFF', '\x15', '*', 'H', '\xFF', 'f', 'm', 
    '\xB0', '\xFF', '\xC6', '\xA3', '\xEF', '\xFF', '\xC6', '\xA3', '\xEF', '\xFF', '\xC6', '\xA3', '\xEF', '\xFC', '\x16', '>', 
    'y', '\xFC', '!', 'X', '\xAA', '\xFF', '\x1C', 'M', '\x96', '\xFF', '\x18', '=', '{', '\xFF', '\x10', ')', 
    'O', '\xFF', '\x1A', '?', '}', '\xFF', ' ', '<', 'f', '\xFF', 'o', '\x8A', '\xB9', '\xFF', '$', 'V', 
    '\x9F', '\xFF', 'd', '}', '\xAE', '\xFF', '\xD6', '\xE0', '\xFF', '\xFF', '\xD4', '\xDD', '\xFF', '\xFF', '\xD9', '\xE0', 
    '\xFF', '\xFF', '\xDE', '\xE6', '\xFF', '\xFF', '\xDE', '\xE8', '\xFF', '\xFF', '\xDE', '\xEA', '\xFF', '\xFF', '\xE0', '\xEB', 
    '\xFF', '\xFF', '\xE2', '\xEB', '\xFF', '\xFF', '\xDF', '\xEB', '\xFF', '\xFF', '\xDD', '\xE9', '\xFF', '\xFF', '\x9D', '\xA0', 
    '\xAD', '\xFF', '\x99', '\x81', '`', '\xFF', '_', ']', 'X', '\xFF', '\xB3', '\xB7', '\xC0', '\xFF', '\x88', '\x98', 
    '\xB5', '\xFF', '\x1A', 'I', '\x90', '\xFF', ' ', 'R', '\xA2', '\xFF', '\x0E', '%', 'E', '\xFF', '(', 'D', 
    '{', '\xFF', '\xC3', '\xA1', '\xE7', '\xFF', '\xCA', '\xA7', '\xEF', '\xFF', '\xCA', '\xA7', '\xEF', '\xFC', '\x1D', 'P', 
    '\x9C', '\xFC', '\x10', ',', 'W', '\xFF', '\x1D', 'I', '\x91', '\xFF', '\x1A', 'F', '\x89', '\xFF', '\x17', ':', 
    'u', '\xFF', '\x1B', 'B', '\x83', '\xFF', '\x1C', 'D', '\x85', '\xFF', 'b', '{', '\xA2', '\xFF', '\x1F', 'V', 
    '\xA6', '\xFF', '\x82', '\x97', '\xC0', '\xFF', '\xD0', '\xD8', '\xE9', '\xFF', 'z', 'z', '\x80', '\xFF', '\x91', 'o', 
    'E', '\xFF', '\x85', 'z', 'b', '\xFF', '\xCF', '\xD6', '\xE5', '\xFF', '\xE0', '\xEB', '\xFE', '\xFF', '\xC1', '\xCB', 
    '\xDD', '\xFF', '\xE0', '\xEB', '\xFF', '\xFF', '\xE2', '\xEB', '\xFF', '\xFF', '\xDE', '\xE7', '\xFA', '\xFF', ']', 'I', 
    '=', '\xFF', '\x81', 'l', 'Q', '\xFF', '\x81', 'a', '@', '\xFF', '_', '_', '`', '\xFF', 'B', 'J', 
    'V', '\xFF', '9', 'c', '\xA5', '\xFF', '\x1B', 'H', '\x8E', '\xFF', '\x17', '7', 'm', '\xFF', '\x15', '2', 
    '_', '\xFF', '\xA4', '\x90', '\xD2', '\xFF', '\xCE', '\xAA', '\xF2', '\xFF', '\xCE', '\xAA', '\xF2', '\xFC', '\x1D', 'P', 
    '\x9C', '\xFC', '\x1A', 'D', '\x86', '\xFF', '\x0F', '$', 'E', '\xFF', '\x1A', '@', '\x80', '\xFF', '\x19', '>', 
    'z', '\xFF', '\x1E', 'N', '\x99', '\xFF', '\x1E', 'K', '\x96', '\xFF', '\x14', '2', '_', '\xFF', '\x1E', 'Q', 
    '\x9F', '\xFF', 'n', '\x85', '\xA9', '\xFF', 'v', 'v', 'y', '\xFF', '^', 'P', 'I', '\xFF', 'z', '`', 
    'I', '\xFF', '\x88', 'a', '@', '\xFF', '~', '\x80', '\x86', '\xFF', '\xA6', '\xB1', '\xCD', '\xFF', '\xC5', '\xCF', 
    '\xE2', '\xFF', '\xE1', '\xEB', '\xFF', '\xFF', '\xE0', '\xEB', '\xFF', '\xFF', '\x9F', '\xA7', '\xB4', '\xFF', '\xAA', '\xA9', 
    '\xAB', '\xFF', '\xDA', '\xD0', '\xCE', '\xFF', 'F', '0', '+', '\xFF', '\x18', '\x1B', '\x1D', '\xFF', '\xAB', '\xB5', 
    '\xC9', '\xFF', 'i', '\x88', '\xB9', '\xFF', '\x1F', 'U', '\xA5', '\xFF', '\x1A', 'A', '\x80', '\xFF', '\x10', '(', 
    'M', '\xFF', 'w', 'w', '\xB8', '\xFF', '\xCE', '\xAE', '\xF7', '\xFF', '\xCE', '\xAE', '\xF7', '\xFC', 'q', '~', 
    '\xBF', '\xFC', '-', '[', '\xAA', '\xFF', '\x18', '=', 'y', '\xFF', '\x13', '1', '_', '\xFF', '\x15', '4', 
    'd', '\xFF', '!', 'X', '\xAB', '\xFF', ' ', 'O', '\x98', '\xFF', '\x18', ';', 'p', '\xFF', ' ', 'U', 
    '\xA1', '\xFF', 'n', '\x87', '\xAF', '\xFF', '9', '=', 'B', '\xFF', '\xBA', '\xB9', '\xBA', '\xFF', '\xB6', '\xA3', 
    '\x9F', '\xFF', 'B', '(', '\x1F', '\xFF', '5', ':', '=', '\xFF', '^', '\x7F', '\xB1', '\xFF', '\xB0', '\xBB', 
    '\xD2', '\xFF', '\xDE', '\xEA', '\xFF', '\xFF', '\xE2', '\xEB', '\xFF', '\xFF', '\xCB', '\xD4', '\xE6', '\xFF', 'h', 'l', 
    'r', '\xFF', 'B', 'G', 'L', '\xFF', '.', '3', '7', '\xFF', '\xA4', '\xAD', '\xBD', '\xFF', '\xDB', '\xE6', 
    '\xFF', '\xFF', '\x93', '\xA7', '\xCC', '\xFF', ' ', ']', '\xAF', '\xFF', '\x1D', 'K', '\x91', '\xFF', '\x11', ')', 
    'K', '\xFF', 'M', ']', '\x9C', '\xFF', '\xD1', '\xB4', '\xF7', '\xFF', '\xD0', '\xB2', '\xF7', '\xFC', '\xD0', '\xB5', 
    '\xF5', '\xFC', '\xB5', '\xA5', '\xE1', '\xFF', 'R', 'o', '\xB3', '\xFF', '\x1D', 'D', 'z', '\xFF', '\x1D', 'I', 
    '\x88', '\xFF', '!', '\\', '\xAC', '\xFF', '!', 'X', '\xA4', '\xFF', '\x1B', '@', 's', '\xFF', '!', 'Z', 
    '\xA5', '\xFF', 'v', '\x95', '\xC3', '\xFF', '\xBB', '\xC7', '\xDC', '\xFF', '\\', 'b', 'k', '\xFF', '#', '-', 
    ':', '\xFF', 'R', 'U', 'Y', '\xFF', '\x8D', '\x97', '\xA9', '\xFF', '/', 'a', '\xA8', '\xFF', '0', 'M', 
    'w', '\xFF', '\xC4', '\xCF', '\xE4', '\xFF', '\xDB', '\xE6', '\xFA', '\xFF', '\xE4', '\xEB', '\xFF', '\xFF', '\xC1', '\xCD', 
    '\xE3', '\xFF', '\xD2', '\xDA', '\xEA', '\xFF', '\xE2', '\xEB', '\xFF', '\xFF', '\xDF', '\xEA', '\xFF', '\xFF', '\xDE', '\xE8', 
    '\xFF', '\xFF', '\xAA', '\xBB', '\xDB', '\xFF', '"', '\\', '\xAC', '\xFF', '\x1F', 'U', '\x9D', '\xFF', '\x1A', '8', 
    'c', '\xFF', '9', 'V', '\x96', '\xFF', '\xD6', '\xB9', '\xF5', '\xFF', '\xD6', '\xB8', '\xF7', '\xFC', '\xD7', '\xBC', 
    '\xF7', '\xFC', '\xD7', '\xBE', '\xF7', '\xFF', '\xD1', '\xBA', '\xF1', '\xFF', 'm', '\x81', '\xC0', '\xFF', '(', 'Y', 
    '\x9C', '\xFF', '\'', 'Z', '\xA0', '\xFF', ')', '`', '\xAE', '\xFF', '"', 'C', 'r', '\xFF', ')', 'c', 
    '\xB2', '\xFF', 'b', '\x86', '\xBA', '\xFF', '\xD9', '\xE4', '\xFC', '\xFF', '\xDC', '\xE6', '\xFE', '\xFF', 'c', '~', 
    '\xA7', '\xFF', '\xC4', '\xCE', '\xE0', '\xFF', '\xCE', '\xD9', '\xED', '\xFF', '(', '_', '\xAD', '\xFF', '$', 'K', 
    '\x81', '\xFF', 'T', 's', '\x9F', '\xFF', '\xBB', '\xC7', '\xDB', '\xFF', '\xD8', '\xE2', '\xF6', '\xFF', '\xE6', '\xEB', 
    '\xFF', '\xFF', '\xE7', '\xEB', '\xFF', '\xFF', '\xE7', '\xEB', '\xFF', '\xFF', '\xE1', '\xEB', '\xFF', '\xFF', '\xCB', '\xD5', 
    '\xE6', '\xFF', '\xAE', '\xBF', '\xDE', '\xFF', '*', '_', '\xA7', '\xFF', ')', 'c', '\xB3', '\xFF', '$', 'L', 
    '\x85', '\xFF', '6', '[', '\x9B', '\xFF', '\xD1', '\xB8', '\xED', '\xFF', '\xD6', '\xBE', '\xF7', '\xFC', '\xDE', '\xC2', 
    '\xF7', '\xFC', '\xDE', '\xC2', '\xF7', '\xFF', '\xDD', '\xC2', '\xF7', '\xFF', '\xDB', '\xC1', '\xF4', '\xFF', 'm', 'y', 
    '\xAD', '\xFF', '3', 'k', '\xB6', '\xFF', '2', 'i', '\xB5', '\xFF', '(', 'F', 'p', '\xFF', '1', 'i', 
    '\xB4', '\xFF', 'C', 'n', '\xA9', '\xFF', '\xD4', '\xE1', '\xF9', '\xFF', '\xD6', '\xE1', '\xF7', '\xFF', ';', 'c', 
    '\x9B', '\xFF', '\xE0', '\xEB', '\xFF', '\xFF', '\xBC', '\xC9', '\xE1', '\xFF', '0', 'k', '\xB6', '\xFF', '-', '[', 
    '\x98', '\xFF', '0', 'c', '\xA8', '\xFF', '\x8D', '\xA4', '\xC8', '\xFF', '\x8C', '\x9D', '\xBC', '\xFF', '\xCB', '\xD4', 
    '\xE6', '\xFF', '\xE4', '\xEC', '\xFF', '\xFF', '\xE7', '\xED', '\xFF', '\xFF', '\xCE', '\xD6', '\xE6', '\xFF', '\xD0', '\xD9', 
    '\xEB', '\xFF', '\xB1', '\xC3', '\xE5', '\xFF', '1', 'd', '\xA7', '\xFF', '2', 'k', '\xB5', '\xFF', '/', 'a', 
    '\xA6', '\xFF', 'A', 'f', '\xA7', '\xFF', '\xDA', '\xBF', '\xF1', '\xFF', '\xDE', '\xC2', '\xF7', '\xFC', '\xDE', '\xC6', 
    '\xF7', '\xFC', '\xDE', '\xC6', '\xF7', '\xFF', '\xD9', '\xC1', '\xF0', '\xFF', '\xCF', '\xB6', '\xE2', '\xFF', '\xD0', '\xBA', 
    '\xE7', '\xFF', 'I', 'w', '\xBB', '\xFF', ';', 'r', '\xBB', '\xFF', '3', 'P', 'y', '\xFF', '9', 'n', 
    '\xB7', '\xFF', '9', 'l', '\xB2', '\xFF', '\xA8', '\xB7', '\xD1', '\xFF', '\xAB', '\xB8', '\xCD', '\xFF', '7', 'i', 
    '\xB0', '\xFF', '\xC3', '\xCE', '\xE2', '\xFF', '\x82', '\x93', '\xB0', '\xFF', ':', 'q', '\xBD', '\xFF', '9', 'n', 
    '\xB7', '\xFF', '6', 'd', '\xA2', '\xFF', '?', 'n', '\xAF', '\xFF', 'p', '\x8E', '\xBB', '\xFF', '\xA5', '\xB4', 
    '\xCD', '\xFF', '\xA6', '\xB2', '\xC8', '\xFF', '\xBE', '\xC9', '\xDB', '\xFF', '\xDD', '\xE8', '\xFB', '\xFF', '\xDD', '\xE7', 
    '\xFF', '\xFF', '\x8F', '\xA0', '\xBC', '\xFF', ';', 'o', '\xB5', '\xFF', '<', 's', '\xBD', '\xFF', ';', 'q', 
    '\xBB', '\xFF', 'U', 'x', '\xB8', '\xFF', '\xDF', '\xC8', '\xF7', '\xFF', '\xDE', '\xC6', '\xF7', '\xFC', '\xDE', '\xCB', 
    '\xF7', '\xFC', '\xDE', '\xCB', '\xF7', '\xFF', '\xD7', '\xC4', '\xE7', '\xFF', '\xC9', '\xA3', '\xD5', '\xFF', '\xD4', '\xBE', 
    '\xE9', '\xFF', '\x83', '\x96', '\xCE', '\xFF', 'E', '|', '\xC4', '\xFF', '?', 'd', '\x98', '\xFF', 'A', 'l', 
    '\xAA', '\xFF', 'D', 'w', '\xBE', '\xFF', '}', '\x94', '\xBA', '\xFF', '\xA5', '\xB7', '\xD6', '\xFF', 'D', 'x', 
    '\xC0', '\xFF', '\xA2', '\xB3', '\xCC', '\xFF', '\xB7', '\xC6', '\xE0', '\xFF', 'D', 'x', '\xBF', '\xFF', 'D', 'v', 
    '\xBD', '\xFF', '@', 'l', '\xAA', '\xFF', 'D', 'w', '\xBD', '\xFF', '\\', '|', '\xAA', '\xFF', 'n', '\x90', 
    '\xBE', '\xFF', '\xDE', '\xE9', '\xFF', '\xFF', '\xE0', '\xEB', '\xFF', '\xFF', '\xDF', '\xEB', '\xFF', '\xFF', '\xDA', '\xE5', 
    '\xFC', '\xFF', '`', 'q', '\x8D', '\xFF', 'E', '{', '\xC2', '\xFF', 'E', '\x7F', '\xC7', '\xFF', 'G', '\x82', 
    '\xC9', '\xFF', 'r', '\x8B', '\xC4', '\xFF', '\xDF', '\xCC', '\xF8', '\xFF', '\xDE', '\xCB', '\xF7', '\xFC', '\xC8', '\xB7', 
    '\xDC', '\xFC', '\xE5', '\xD1', '\xF9', '\xFF', '\xDE', '\xCA', '\xEA', '\xFF', '\xD6', '\xB5', '\xE0', '\xFF', '\xC1', '\x9B', 
    '\xCE', '\xFF', '\xB8', '\xB0', '\xDC', '\xFF', 'R', '\x88', '\xC9', '\xFF', 'L', '}', '\xBD', '\xFF', 'I', 'k', 
    '\x9C', '\xFF', 'L', '}', '\xBD', '\xFF', 'T', 'q', '\x99', '\xFF', '\x84', '\x9C', '\xC3', '\xFF', 'M', '\x7F', 
    '\xC1', '\xFF', '~', '\x9D', '\xC9', '\xFF', '\xC2', '\xD1', '\xEA', '\xFF', 'K', '~', '\xC1', '\xFF', 'M', '\x7F', 
    '\xC2', '\xFF', 'K', 'w', '\xB3', '\xFF', 'M', '~', '\xC0', '\xFF', 'U', '~', '\xB5', '\xFF', 'Q', 'y', 
    '\xAD', '\xFF', '\xC0', '\xCD', '\xE8', '\xFF', '\xDE', '\xEA', '\xFF', '\xFF', '\xDC', '\xE7', '\xFE', '\xFF', '\xAD', '\xB9', 
    '\xCE', '\xFF', 'H', 'd', '\x88', '\xFF', 'O', '\x8A', '\xCC', '\xFF', 'S', '\x92', '\xD2', '\xFF', 'W', '\x91', 
    '\xCC', '\xFF', '\x9A', '\xA1', '\xD0', '\xFF', '\xE4', '\xD0', '\xF7', '\xFF', '\xE4', '\xD0', '\xF7', '\xFC', 'V', 'c', 
    'y', '\xFC', '\x8F', '\x8B', '\xA8', '\xFF', '\xDC', '\xCA', '\xE5', '\xFF', '\xE3', '\xCA', '\xED', '\xFF', '\xC5', '\x98', 
    '\xD0', '\xFF', '\xC0', '\x9E', '\xCC', '\xFF', 'h', '\x8D', '\xC4', '\xFF', 'W', '\x8B', '\xCB', '\xFF', 'S', '{', 
    '\xB0', '\xFF', 'V', '\x85', '\xC5', '\xFF', 'U', '}', '\xB5', '\xFF', 'b', 's', '\x8F', '\xFF', 'V', '\x86', 
    '\xC7', '\xFF', '[', '\x85', '\xBC', '\xFF', '\xBE', '\xCD', '\xE6', '\xFF', 'V', '\x86', '\xC2', '\xFF', 'V', '\x8A', 
    '\xC8', '\xFF', 'V', '\x88', '\xC7', '\xFF', 'U', '\x83', '\xBE', '\xFF', 'V', '\x86', '\xC4', '\xFF', '\\', '\x80', 
    '\xB1', '\xFF', '\x85', '\xA1', '\xC8', '\xFF', '\xD8', '\xE3', '\xF8', '\xFF', '\x9E', '\xAA', '\xBD', '\xFF', 'S', 'e', 
    '}', '\xFF', '\\', '\x8D', '\xC1', '\xFF', ']', '\x99', '\xD5', '\xFF', 'h', '\xA9', '\xDD', '\xFF', 'c', '\x90', 
    '\xC8', '\xFF', '\xCD', '\xC2', '\xE9', '\xFF', '\xE7', '\xD4', '\xFC', '\xFF', '\xE7', '\xD4', '\xF9', '\xFC', '[', 'k', 
    '\x85', '\xFC', 'i', 't', '\x87', '\xFF', '\xEC', '\xDB', '\xF5', '\xFF', '\xDD', '\xC8', '\xE7', '\xFF', '\xBB', '\x9A', 
    '\xC7', '\xFF', '\xBD', '\x95', '\xC9', '\xFF', '\x91', '\x8D', '\xC1', '\xFF', 'g', '\x9B', '\xD5', '\xFF', 'a', '\x90', 
    '\xCA', '\xFF', 'a', '\x8D', '\xC8', '\xFF', '`', '\x8D', '\xC9', '\xFF', '[', 't', '\x96', '\xFF', '`', '\x8A', 
    '\xC3', '\xFF', 'a', '\x92', '\xCE', '\xFF', '\x89', '\xA1', '\xC5', '\xFF', 'k', '\x95', '\xC7', '\xFF', 'c', '\x96', 
    '\xD1', '\xFF', 'b', '\x93', '\xCE', '\xFF', 'a', '\x90', '\xCB', '\xFF', 'c', '\x92', '\xCE', '\xFF', '_', '\x87', 
    '\xBA', '\xFF', 'm', '\x90', '\xC0', '\xFF', '\xC0', '\xCF', '\xEA', '\xFF', 'q', '\x81', '\x97', '\xFF', '_', '\x82', 
    '\xAF', '\xFF', 'f', '\x9B', '\xD7', '\xFF', 'd', '\x9A', '\xD3', '\xFF', 'e', '\x9B', '\xD3', '\xFF', '\x9D', '\xA8', 
    '\xD2', '\xFF', '\xE3', '\xD6', '\xFB', '\xFF', '\xE7', '\xD7', '\xFE', '\xFF', '\xE7', '\xD7', '\xFE', '\xFC', '\x8B', '\x92', 
    '\xA8', '\xFC', '\xD6', '\xC9', '\xE5', '\xFF', '\xDC', '\xC0', '\xE6', '\xFF', '\xCD', '\xAA', '\xD9', '\xFF', '\xCC', '\xB0', 
    '\xD7', '\xFF', '\xC7', '\xA1', '\xD2', '\xFF', '\xB8', '\x97', '\xC7', '\xFF', '}', '\x9F', '\xCE', '\xFF', 'o', '\xA2', 
    '\xD8', '\xFF', 'n', '\x9D', '\xD4', '\xFF', 'l', '\x9A', '\xD2', '\xFF', 'k', '\x94', '\xCB', '\xFF', 'j', '\x8E', 
    '\xBC', '\xFF', 'n', '\x9E', '\xD5', '\xFF', 'p', '\x91', '\xBA', '\xFF', 'v', '\x95', '\xBD', '\xFF', 'y', '\xAD', 
    '\xDD', '\xFF', 'p', '\xA1', '\xD7', '\xFF', 'l', '\x9A', '\xD3', '\xFF', 'o', '\x9E', '\xD5', '\xFF', 'n', '\x96', 
    '\xC9', '\xFF', 'j', '\x92', '\xC8', '\xFF', 'd', 'r', '\x85', '\xFF', 'h', '\x84', '\xAA', '\xFF', 'l', '\x99', 
    '\xD2', '\xFF', 'l', '\x99', '\xD1', '\xFF', 'l', '\x97', '\xCD', '\xFF', '\x86', '\x9E', '\xCA', '\xFF', '\xE0', '\xD3', 
    '\xF3', '\xFF', '\xE9', '\xDA', '\xFC', '\xFF', '\xEC', '\xDB', '\xFD', '\xFF', '\xEC', '\xDB', '\xFE', '\xFC', '\x93', '\xA8', 
    '\xCD', '\xFC', '\x93', '\xA2', '\xC3', '\xFF', '\x9D', '\xA1', '\xB7', '\xFF', '\xBD', '\xB3', '\xCC', '\xFF', '\xD4', '\xC3', 
    '\xDE', '\xFF', '\xE0', '\xC6', '\xEA', '\xFF', '\xD1', '\xAC', '\xDC', '\xFF', '\xB1', '\xA3', '\xD5', '\xFF', '\x85', '\xB8', 
    '\xE5', '\xFF', '\x7F', '\xB2', '\xE1', '\xFF', '|', '\xAD', '\xDE', '\xFF', 'w', '\xA5', '\xD9', '\xFF', 'v', '\xA2', 
    '\xD5', '\xFF', '|', '\xAD', '\xDD', '\xFF', 'x', '\xA4', '\xD6', '\xFF', 'q', '\x86', '\xA1', '\xFF', '{', '\xA7', 
    '\xDA', '\xFF', 'x', '\xA3', '\xD7', '\xFF', 'u', '\x9F', '\xD6', '\xFF', 'u', '\x9E', '\xD5', '\xFF', 'u', '\x9D', 
    '\xD2', '\xFF', 't', '\x9B', '\xCF', '\xFF', 'q', '\x86', '\xA5', '\xFF', 't', '\x98', '\xC9', '\xFF', 'u', '\x9D', 
    '\xD0', '\xFF', 'v', '\x8E', '\xB1', '\xFF', '\xA4', '\xAB', '\xCD', '\xFF', '\xDE', '\xD4', '\xF3', '\xFF', '\xE9', '\xDD', 
    '\xFD', '\xFF', '\xEF', '\xDF', '\xFF', '\xFF', '\xEF', '\xDF', '\xFF', '\xFF', '\xEF', '\xDF', '\xFF', '\xFC', '~', '\x9F', 
    '\xCE', '\xFC', '~', '\xA1', '\xD2', '\xFF', '\x7F', '\x9E', '\xCC', '\xFF', '}', '\x90', '\xAD', '\xFF', '\x87', '\x8F', 
    '\xA2', '\xFF', '\xED', '\xE1', '\xF6', '\xFF', '\xE9', '\xD8', '\xF2', '\xFF', '\xDB', '\xBE', '\xE5', '\xFF', '\xA2', '\xAB', 
    '\xD7', '\xFF', '\x89', '\xB9', '\xE6', '\xFF', '\x84', '\xB2', '\xE1', '\xFF', '\x83', '\xAF', '\xDF', '\xFF', '\x80', '\xAA', 
    '\xDE', '\xFF', '\x80', '\xAA', '\xD9', '\xFF', '\x7F', '\xA8', '\xD6', '\xFF', '}', '\x9C', '\xC6', '\xFF', '}', '\x9C', 
    '\xC6', '\xFF', '~', '\xA4', '\xD6', '\xFF', '~', '\xA4', '\xD6', '\xFF', '\x7F', '\xA4', '\xD6', '\xFF', '\x7F', '\xA3', 
    '\xD6', '\xFF', '\x7F', '\xA3', '\xD4', '\xFF', '\x80', '\xA2', '\xD3', '\xFF', '\x7F', '\xA2', '\xD5', '\xFF', '\x80', '\xA2', 
    '\xD2', '\xFF', '\xB8', '\xB7', '\xD2', '\xFF', '\xEB', '\xE1', '\xFE', '\xFF', '\xEF', '\xE2', '\xFF', '\xFF', '\xEF', '\xE2', 
    '\xFF', '\xFF', '\xEF', '\xE2', '\xFF', '\xFF', '\xEF', '\xE2', '\xFF', '\xFF', '\xEF', '\xE2', '\xFF', '\xFC', '\x88', '\xA5', 
    '\xD0', '\xFC', '\x87', '\xA3', '\xCB', '\xFF', '\x88', '\xA6', '\xD0', '\xFF', '\x88', '\xAB', '\xD8', '\xFF', '\x89', '\xA0', 
    '\xC2', '\xFF', '\xD3', '\xCB', '\xDF', '\xFF', '\xF2', '\xE6', '\xFA', '\xFF', '\xEF', '\xE3', '\xF7', '\xFF', '\xE9', '\xD8', 
    '\xF3', '\xFF', '\xB0', '\xBA', '\xDE', '\xFF', '\x8A', '\xB2', '\xDD', '\xFF', '\x8A', '\xB0', '\xDE', '\xFF', '\x89', '\xAE', 
    '\xDE', '\xFF', '\x89', '\xAD', '\xDC', '\xFF', '\x88', '\xAC', '\xD6', '\xFF', '\x88', '\xAA', '\xD6', '\xFF', '\x87', '\xA1', 
    '\xC5', '\xFF', '\x87', '\xA5', '\xD1', '\xFF', '\x88', '\xA9', '\xD6', '\xFF', '\x88', '\xA9', '\xD6', '\xFF', '\x88', '\xA9', 
    '\xD6', '\xFF', '\x88', '\xA9', '\xD6', '\xFF', '\x88', '\xA9', '\xD6', '\xFF', '\x89', '\xA9', '\xD6', '\xFF', '\xA8', '\xB6', 
    '\xDA', '\xFF', '\xEC', '\xE3', '\xFB', '\xFF', '\xEF', '\xE6', '\xFF', '\xFF', '\xEF', '\xE6', '\xFF', '\xFF', '\xEF', '\xE6', 
    '\xFF', '\xFF', '\xEF', '\xE6', '\xFF', '\xFF', '\xEF', '\xE6', '\xFF', '\xFF', '\xEF', '\xE6', '\xFF', '\xFC', '\x91', '\xB0', 
    '\xDA', '\xFC', '\x91', '\xAF', '\xD9', '\xFF', '\x91', '\xA9', '\xCD', '\xFF', '\x8E', '\x9F', '\xB8', '\xFF', '\x8D', '\x9D', 
    '\xB3', '\xFF', '\xDF', '\xD6', '\xE9', '\xFF', '\xDB', '\xC6', '\xE5', '\xFF', '\xDC', '\xCA', '\xE5', '\xFF', '\xDF', '\xCF', 
    '\xE8', '\xFF', '\xE2', '\xD4', '\xEA', '\xFF', '\xC4', '\xB7', '\xDE', '\xFF', '\x9B', '\xB1', '\xD8', '\xFF', '\x92', '\xB3', 
    '\xDE', '\xFF', '\x92', '\xB2', '\xDE', '\xFF', '\x93', '\xB0', '\xDE', '\xFF', '\x92', '\xB0', '\xDB', '\xFF', '\x91', '\xAF', 
    '\xD9', '\xFF', '\x91', '\xAB', '\xD1', '\xFF', '\x91', '\xAF', '\xD8', '\xFF', '\x91', '\xAF', '\xD9', '\xFF', '\x91', '\xAF', 
    '\xD7', '\xFF', '\x92', '\xAF', '\xD6', '\xFF', '\x97', '\xB1', '\xD8', '\xFF', '\xC0', '\xC5', '\xE3', '\xFF', '\xF1', '\xE4', 
    '\xFA', '\xFF', '\xF6', '\xE8', '\xFF', '\xFF', '\xF6', '\xE8', '\xFF', '\xFF', '\xF5', '\xE8', '\xFF', '\xFF', '\xF6', '\xE8', 
    '\xFF', '\xFF', '\xF6', '\xE8', '\xFF', '\xFF', '\xF5', '\xE8', '\xFF', '\xFF', '\xF6', '\xE8', '\xFF', '\xFC', '\x9A', '\xB6', 
    '\xDE', '\xFC', '\x9A', '\xB7', '\xDE', '\xFF', '\x9B', '\xB8', '\xDF', '\xFF', '\x9B', '\xB9', '\xE1', '\xFF', '\xA8', '\xB7', 
    '\xD1', '\xFF', '\xF7', '\xED', '\xFF', '\xFF', '\xF3', '\xE6', '\xFB', '\xFF', '\xF0', '\xE0', '\xF8', '\xFF', '\xEC', '\xE1', 
    '\xF5', '\xFF', '\xC4', '\xC7', '\xDF', '\xFF', '\xF0', '\xE2', '\xF8', '\xFF', '\xE6', '\xD9', '\xEF', '\xFF', '\xCB', '\xC9', 
    '\xE8', '\xFF', '\xAA', '\xB9', '\xDF', '\xFF', '\x9B', '\xB5', '\xDB', '\xFF', '\x99', '\xB6', '\xDF', '\xFF', '\x9A', '\xB6', 
    '\xE0', '\xFF', '\x9D', '\xB6', '\xE0', '\xFF', '\x9E', '\xB6', '\xDF', '\xFF', '\xA4', '\xB8', '\xDD', '\xFF', '\xB3', '\xBF', 
    '\xDF', '\xFF', '\xCD', '\xCF', '\xE8', '\xFF', '\xEA', '\xE1', '\xF6', '\xFF', '\xF7', '\xEC', '\xFF', '\xFF', '\xF7', '\xEB', 
    '\xFF', '\xFF', '\xF7', '\xEB', '\xFF', '\xFF', '\xF7', '\xEB', '\xFF', '\xFF', '\xF7', '\xEB', '\xFF', '\xFF', '\xF7', '\xEB', 
    '\xFF', '\xFF', '\xF7', '\xEB', '\xFF', '\xFF', '\xF7', '\xEB', '\xFF', '\xFF', '\xF7', '\xEB', '\xFF', '\xFC', '\xA3', '\xBD', 
    '\xE0', '\xF0', '\xA2', '\xBE', '\xE3', '\xFC', '\xA3', '\xBF', '\xE6', '\xFC', '\xA2', '\xC1', '\xE7', '\xFC', '\xD5', '\xD7', 
    '\xEC', '\xFC', '\xF7', '\xF0', '\xFF', '\xFC', '\xF0', '\xE9', '\xF8', '\xFC', '\xCA', '\xD0', '\xE6', '\xFC', '\xA5', '\xBB', 
    '\xDB', '\xFC', '\xA2', '\xBB', '\xDE', '\xFC', '\xC2', '\xC4', '\xD8', '\xFC', '\xEE', '\xE4', '\xF4', '\xFC', '\xE4', '\xD9', 
    '\xEB', '\xFC', '\xF2', '\xE4', '\xFA', '\xFC', '\xEF', '\xE1', '\xF9', '\xFC', '\xE6', '\xDD', '\xF3', '\xFC', '\xDD', '\xD7', 
    '\xEA', '\xFC', '\xEA', '\xE4', '\xF5', '\xFC', '\xF1', '\xE9', '\xF9', '\xFC', '\xF6', '\xEE', '\xFE', '\xFC', '\xF7', '\xEF', 
    '\xFF', '\xFC', '\xF7', '\xEF', '\xFF', '\xFC', '\xF7', '\xEF', '\xFF', '\xFC', '\xF7', '\xEF', '\xFF', '\xFC', '\xF7', '\xEF', 
    '\xFF', '\xFC', '\xF7', '\xEF', '\xFF', '\xFC', '\xF7', '\xEF', '\xFF', '\xFC', '\xF7', '\xEF', '\xFF', '\xFC', '\xF7', '\xEF', 
    '\xFF', '\xFC', '\xF7', '\xEF', '\xFF', '\xFC', '\xF7', '\xEF', '\xFF', '\xFC', '\xF7', '\xEF', '\xFF', '\xF0', '\0', '\0', 
    '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', 
    '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', 
    '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', 
    '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', 
    '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', 
    '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', 
    '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', 
    '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0'
};

const char Icon_16x16[] = {
    '\0', '\0', '\x01', '\0', '\x01', '\0', '\x10', '\x10', '\0', '\0', '\x01', '\0', ' ', '\0', 'h', '\x04', 
    '\0', '\0', '\x16', '\0', '\0', '\0', '(', '\0', '\0', '\0', '\x10', '\0', '\0', '\0', ' ', '\0', 
    '\0', '\0', '\x01', '\0', ' ', '\0', '\0', '\0', '\0', '\0', '\0', '\x04', '\0', '\0', '\0', '\0', 
    '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\xB5', '\x86', 
    '\xEF', '\xFA', '\xB1', '\x84', '\xE5', '\xFE', '\xAA', '\x84', '\xD0', '\xFE', '\xA3', '~', '\xC0', '\xFE', 'X', '(', 
    '{', '\xFE', 'A', ')', 'f', '\xFE', '\x95', '\x7F', '\x99', '\xFE', 'h', 'T', 's', '\xFE', 'J', '2', 
    'b', '\xFE', ']', 'e', '\x88', '\xFE', '\x8D', '~', '\x96', '\xFE', '\xB9', '\xAD', '\xB4', '\xFE', '\xE2', '\xDE', 
    '\xDF', '\xFE', '\xEA', '\xE4', '\xE4', '\xFE', '\xDF', '\xD8', '\xE0', '\xFE', '\xBB', '\x9B', '\xDF', '\xFA', '\xB5', '\x89', 
    '\xEF', '\xFE', '\x8D', 's', '\xC6', '\xFF', 'e', '_', '\xA7', '\xFF', '\x9B', 'v', '\xCC', '\xFF', '\x8E', 'g', 
    '\xB6', '\xFF', '\x8A', 'r', '\x9A', '\xFF', '\xA7', '\x9B', '\xA3', '\xFF', '\x96', '\xA0', '\xC0', '\xFF', '\xBE', '\xAB', 
    '\xAC', '\xFF', '\xA9', '\xA2', '\xAE', '\xFF', '\x1D', '8', ']', '\xFF', ']', 'T', '\x86', '\xFF', '\xB7', '\x9B', 
    '\xD5', '\xFF', '\xCC', '\xB3', '\xDE', '\xFF', '\xBD', '\x99', '\xE8', '\xFF', '\xB5', '\x88', '\xEF', '\xFE', '\xB9', '\x8D', 
    '\xEF', '\xFE', 'g', 'f', '\xB0', '\xFF', '\x11', ',', 'U', '\xFF', '\x0E', '%', 'E', '\xFF', '\x15', '&', 
    'B', '\xFF', '0', '7', 'Z', '\xFF', 'l', 'u', '\x8B', '\xFF', '\xBB', '\xC9', '\xE6', '\xFF', '\xCE', '\xDA', 
    '\xF1', '\xFF', '\xAF', '\xB8', '\xCE', '\xFF', '<', 'Y', '\x84', '\xFF', '%', '=', 'o', '\xFF', '\xAD', '\x88', 
    '\xE4', '\xFF', '\xB8', '\x8D', '\xEF', '\xFF', '\xB8', '\x8D', '\xEF', '\xFF', '\xB8', '\x8C', '\xEF', '\xFE', '\x8F', 'w', 
    '\xC4', '\xFE', 'p', 'a', '\x9F', '\xFF', '\x0E', ')', 'N', '\xFF', '\f', '\'', 'J', '\xFF', '\n', '#', 
    'A', '\xFF', 'P', '`', 'x', '\xFF', '\xD4', '\xDF', '\xF5', '\xFF', '\xD0', '\xDA', '\xF8', '\xFF', '\xBB', '\xC0', 
    '\xF1', '\xFF', '\xDA', '\xE4', '\xFB', '\xFF', '\xD9', '\xE5', '\xFA', '\xFF', 'Y', 'u', '\xA0', '\xFF', 'd', 'i', 
    '\xB4', '\xFF', '\xBD', '\x91', '\xEF', '\xFF', '\xBD', '\x91', '\xEF', '\xFF', '\xBD', '\x92', '\xEF', '\xFE', 'j', 'i', 
    '\xAD', '\xFE', '\x1B', '7', 'j', '\xFF', '\x0F', '\'', 'K', '\xFF', '\t', '!', ';', '\xFF', ')', '<', 
    'V', '\xFF', '\xD4', '\xDE', '\xF4', '\xFF', '\xDE', '\xEA', '\xFF', '\xFF', '\x87', '\x8A', '\xCC', '\xFF', '\x84', '\x85', 
    '\xD4', '\xFF', '\xAF', '\xB5', '\xE1', '\xFF', '\xDC', '\xE5', '\xFF', '\xFF', '\xA5', '\xB2', '\xD1', '\xFF', 'k', '\x84', 
    '\xB1', '\xFF', '\xA7', '\x91', '\xDE', '\xFF', '\xBF', '\x98', '\xEF', '\xFF', '\xBF', '\x98', '\xEF', '\xFE', 'M', '_', 
    '\xA2', '\xFE', '\x13', '/', '[', '\xFF', '\x18', '<', 'v', '\xFF', '(', ':', 'R', '\xFF', 'y', '\x8A', 
    '\xA9', '\xFF', '\xAD', '\xB6', '\xDA', '\xFF', '\xD4', '\xDC', '\xFF', '\xFF', '\xDC', '\xE5', '\xFD', '\xFF', '\xDB', '\xE6', 
    '\xF9', '\xFF', '\xDC', '\xE5', '\xFF', '\xFF', '\xC7', '\xCD', '\xFC', '\xFF', '\xBC', '\xC2', '\xEA', '\xFF', '>', 'e', 
    '\xA5', '\xFF', 'e', 'u', '\xA7', '\xFF', '\xC1', '\x9B', '\xEB', '\xFF', '\xC6', '\x9F', '\xEF', '\xFE', '\x1C', 'Q', 
    '\x9C', '\xFE', '\x17', '=', 'x', '\xFF', '\x16', '5', 'i', '\xFF', 'J', 'b', '\x89', '\xFF', '@', 'd', 
    '\x9F', '\xFF', '\xCE', '\xD6', '\xFE', '\xFF', '\xD6', '\xDD', '\xFF', '\xFF', '\xDE', '\xE8', '\xFF', '\xFF', '\xE1', '\xEB', 
    '\xFF', '\xFF', '\xDE', '\xE9', '\xFF', '\xFF', '\xB8', '\xB6', '\xC3', '\xFF', '\xAB', '\xB0', '\xC1', '\xFF', '@', 'e', 
    '\x9E', '\xFF', ' ', 'A', 's', '\xFF', '\x86', '}', '\xC0', '\xFF', '\xC8', '\xA5', '\xEF', '\xFE', '\x19', 'D', 
    '\x85', '\xFE', '\x18', '=', 'x', '\xFF', '\x1A', 'B', '\x83', '\xFF', ',', 'O', '\x87', '\xFF', 'K', 'q', 
    '\xAC', '\xFF', '\x88', '\x86', '\x8B', '\xFF', '\x86', 'j', 'L', '\xFF', '\xB5', '\xBC', '\xCE', '\xFF', '\xD2', '\xDC', 
    '\xEF', '\xFF', '\xD0', '\xD9', '\xEB', '\xFF', '\x99', '\x8C', '\x82', '\xFF', 'P', 'C', ':', '\xFF', 'd', '{', 
    '\x9F', '\xFF', '\x1B', 'E', '\x88', '\xFF', 'P', 'X', '\x8D', '\xFF', '\xCE', '\xAC', '\xF4', '\xFE', '\x88', '\x8D', 
    '\xD0', '\xFE', '&', 'H', '\x81', '\xFF', '\x1D', 'L', '\x91', '\xFF', '\x1D', 'I', '\x88', '\xFF', 'I', 's', 
    '\xAE', '\xFF', '\x83', '\x88', '\x91', '\xFF', '[', 'S', 'T', '\xFF', 'T', 'l', '\x90', '\xFF', '\xA0', '\xB0', 
    '\xCB', '\xFF', '\xDB', '\xE4', '\xF8', '\xFF', '\x8F', '\x97', '\xA3', '\xFF', '\xA5', '\xAD', '\xBD', '\xFF', '\xBD', '\xCC', 
    '\xE9', '\xFF', ' ', 'V', '\xA2', '\xFF', ',', 'E', 'x', '\xFF', '\xD3', '\xB6', '\xF6', '\xFE', '\xDA', '\xC0', 
    '\xF7', '\xFE', '\xBD', '\xAF', '\xE7', '\xFF', '<', 'f', '\xA8', '\xFF', ')', 'U', '\x91', '\xFF', '@', 'p', 
    '\xB2', '\xFF', '\xD8', '\xE3', '\xFB', '\xFF', '\x91', '\xA6', '\xC8', '\xFF', 'x', '\x9B', '\xCC', '\xFF', '5', '_', 
    '\x98', '\xFF', '\xAB', '\xBA', '\xD5', '\xFF', '\xDF', '\xE6', '\xF9', '\xFF', '\xDF', '\xE6', '\xF9', '\xFF', '\xBF', '\xCC', 
    '\xE5', '\xFF', '.', 'd', '\xAE', '\xFF', '3', '[', '\x9B', '\xFF', '\xD8', '\xBE', '\xF3', '\xFE', '\xDE', '\xC9', 
    '\xF7', '\xFE', '\xD2', '\xB8', '\xE3', '\xFF', '\x9C', '\xA1', '\xD6', '\xFF', '=', 'h', '\xA4', '\xFF', '>', 'o', 
    '\xB4', '\xFF', '\x9D', '\xAF', '\xCC', '\xFF', 'x', '\x98', '\xC8', '\xFF', 'n', '\x90', '\xC3', '\xFF', '=', 'm', 
    '\xB0', '\xFF', 'T', '|', '\xB4', '\xFF', '\xA6', '\xB7', '\xD4', '\xFF', '\xD7', '\xE2', '\xF5', '\xFF', '\xA9', '\xB7', 
    '\xD1', '\xFF', '@', 'w', '\xBF', '\xFF', 'R', '~', '\xC0', '\xFF', '\xDE', '\xC9', '\xF7', '\xFE', '\xA4', '\x9E', 
    '\xBD', '\xFE', '\xDD', '\xC5', '\xE7', '\xFF', '\xC0', '\xA0', '\xD1', '\xFF', 'X', '\x87', '\xC5', '\xFF', 'P', 'z', 
    '\xB4', '\xFF', 'd', '\x7F', '\xA8', '\xFF', '_', '\x8A', '\xC3', '\xFF', '\x88', '\xA9', '\xD5', '\xFF', 'Q', '\x82', 
    '\xC1', '\xFF', 'S', '\x81', '\xBE', '\xFF', '|', '\x9A', '\xC4', '\xFF', '\xCC', '\xD8', '\xEC', '\xFF', 'i', '\x84', 
    '\xA5', '\xFF', 'Z', '\x97', '\xD4', '\xFF', '\x88', '\xA1', '\xD3', '\xFF', '\xE6', '\xD2', '\xF9', '\xFE', '\x89', '\x8F', 
    '\xA6', '\xFE', '\xDC', '\xC3', '\xE7', '\xFF', '\xC3', '\xA0', '\xCE', '\xFF', '\x8B', '\x97', '\xCB', '\xFF', 'h', '\x97', 
    '\xD0', '\xFF', 'e', '\x8C', '\xBF', '\xFF', 'f', '\x92', '\xC8', '\xFF', 'w', '\x97', '\xC1', '\xFF', 'k', '\x9E', 
    '\xD5', '\xFF', 'h', '\x97', '\xD0', '\xFF', 'i', '\x90', '\xC3', '\xFF', '\x7F', '\x91', '\xAC', '\xFF', 'g', '\x94', 
    '\xCA', '\xFF', 'o', '\x9A', '\xCF', '\xFF', '\xD2', '\xCA', '\xEF', '\xFF', '\xE9', '\xD9', '\xFD', '\xFE', '\x88', '\xA3', 
    '\xCC', '\xFE', '\x95', '\xA1', '\xBF', '\xFF', '\xCA', '\xBE', '\xD8', '\xFF', '\xD1', '\xB9', '\xE2', '\xFF', '\x8C', '\xB4', 
    '\xE1', '\xFF', '\x7F', '\xAD', '\xDE', '\xFF', '|', '\xA9', '\xDA', '\xFF', 'y', '\x9C', '\xC5', '\xFF', '{', '\xA2', 
    '\xD3', '\xFF', 'z', '\xA1', '\xD6', '\xFF', 'z', '\x9F', '\xD3', '\xFF', 'y', '\x98', '\xC5', '\xFF', '\x89', '\xA1', 
    '\xC9', '\xFF', '\xD7', '\xD1', '\xEF', '\xFF', '\xEE', '\xE0', '\xFE', '\xFF', '\xEF', '\xE1', '\xFF', '\xFE', '\x8C', '\xAA', 
    '\xD3', '\xFE', '\x8C', '\xA6', '\xCB', '\xFF', '\xB2', '\xB8', '\xCF', '\xFF', '\xE6', '\xD6', '\xEF', '\xFF', '\xD7', '\xCD', 
    '\xE9', '\xFF', '\x9D', '\xB2', '\xDC', '\xFF', '\x8E', '\xB0', '\xDE', '\xFF', '\x8D', '\xAE', '\xD9', '\xFF', '\x8C', '\xA8', 
    '\xD0', '\xFF', '\x8D', '\xAC', '\xD7', '\xFF', '\x8D', '\xAC', '\xD6', '\xFF', '\x9A', '\xB2', '\xDA', '\xFF', '\xDF', '\xD9', 
    '\xF4', '\xFF', '\xF2', '\xE7', '\xFF', '\xFF', '\xF2', '\xE7', '\xFF', '\xFF', '\xF2', '\xE7', '\xFF', '\xFE', '\x9E', '\xBA', 
    '\xE0', '\xFA', '\x9F', '\xBC', '\xE3', '\xFE', '\xDB', '\xDB', '\xEF', '\xFE', '\xE7', '\xE0', '\xF5', '\xFE', '\xBE', '\xC8', 
    '\xE3', '\xFE', '\xE2', '\xD9', '\xED', '\xFE', '\xD3', '\xD0', '\xEB', '\xFE', '\xC2', '\xCA', '\xE9', '\xFE', '\xBF', '\xCA', 
    '\xE8', '\xFE', '\xCA', '\xD1', '\xED', '\xFE', '\xDB', '\xDB', '\xF1', '\xFE', '\xF4', '\xEA', '\xFD', '\xFE', '\xF7', '\xED', 
    '\xFF', '\xFE', '\xF7', '\xED', '\xFF', '\xFE', '\xF7', '\xED', '\xFF', '\xFE', '\xF7', '\xED', '\xFF', '\xFA', '\0', '\0', 
    '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', 
    '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', 
    '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', 
    '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0'
};

inline HICON create_icon_wrapper(const char* icon_data, int icon_size)
{
	HICON out = NULL;
	int offset = LookupIconIdFromDirectoryEx(PBYTE(icon_data), TRUE, icon_size, icon_size, LR_DEFAULTCOLOR);

	if(offset != 0)
		out = CreateIconFromResourceEx(PBYTE(icon_data + offset), 0, TRUE, 0x30000, icon_size, icon_size, LR_DEFAULTCOLOR | LR_SHARED);

	return out;
}

HICON create_icon_32x32()
{
	return create_icon_wrapper(Icon_32x32, 32);
}

HICON create_icon_16x16()
{
	return create_icon_wrapper(Icon_32x32, 16);
}
